---
# Optional method of pinning a specific version of Jenkins and/or overriding the
# default Jenkins packaging URL.
#jenkins_version: "2.118"
# jenkins_pkg_url: "https://www.example.com"

# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_package_state: latest

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

#jenkins_plugins: []
jenkins_plugins:
  - git
  - ssh
  - ansicolor
  - matrix-project
  - extended-read-permission
  - ssh-slaves
  - build-pipeline-plugin
  - packer
  - icon-shim
  - matrix-auth
  - job-dsl
  - credentials
  - ssh-credentials
  - authorize-project
  - github
  - gradle
  - generic-webhook-trigger

jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30
jenkins_plugins_install_dependencies: true
jenkins_updates_url: "https://updates.jenkins.io"

jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_password_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"

# If Jenkins is behind a proxy, configure this.
jenkins_proxy_host: ""
jenkins_proxy_port: ""
jenkins_proxy_noproxy:
  - "127.0.0.1"
  - "localhost"

solita_jenkins_plugins: []
solita_jenkins_users: []
solita_jenkins_absent_users: []
solita_jenkins_jobs_dir: "{{ playbook_dir }}/jobs"
solita_jenkins_security_realm: jenkins
solita_jenkins_jnlp_port: 8081
solita_jenkins_restart: yes