- name: Find remote Job DSL scripts
  find:
    paths: "{{ solita_jenkins_job_dsl_workspace }}"
    patterns: "*.groovy"
    file_type: file
    recurse: yes
  register: find_remote_scripts

- set_fact:
    old_scripts: "{{ find_remote_scripts.files | map(attribute='path') | map('relpath', solita_jenkins_job_dsl_workspace) | list }}"

- name: Find local Job DSL scripts
  become: no
  delegate_to: localhost
  find:
    paths: "{{ solita_jenkins_jobs_dir }}"
    patterns: "*.groovy"
    file_type: file
    recurse: yes
  register: find_local_scripts

- set_fact:
    scripts: "{{ find_local_scripts.files | map(attribute='path') | map('relpath', solita_jenkins_jobs_dir) | list }}"

- name: Create directories for the Job DSL scripts
  become: yes
  file:
    path: "{{ solita_jenkins_job_dsl_workspace }}/{{ item }}"
    state: directory
    owner: jenkins
    group: jenkins
  with_items:
    - "{{ scripts | map('dirname') | unique | list }}"

- name: Copy the Job DSL scripts to the job-dsl workspace
  become: yes
  copy:
    src: "{{ solita_jenkins_jobs_dir }}/{{ item }}"
    dest: "{{ solita_jenkins_job_dsl_workspace }}/{{ item }}"
    owner: jenkins
    group: jenkins
  with_items: "{{ scripts }}"
  register: copy_scripts

- name: Find local Job DSL script templates
  become: no
  delegate_to: localhost
  find:
    paths: "{{ solita_jenkins_jobs_dir }}"
    patterns: "*.groovy.j2"
    file_type: file
    recurse: yes
  register: find_local_templates

- set_fact:
    templates: "{{ find_local_templates.files | map(attribute='path') | map('relpath', solita_jenkins_jobs_dir) | list }}"

- name: Create directories for the Job DSL script templates
  become: yes
  file:
    path: "{{ solita_jenkins_job_dsl_workspace }}/{{ item }}"
    state: directory
    owner: jenkins
    group: jenkins
  with_items:
    - "{{ templates | map('dirname') | unique | list }}"

- name: Copy the Job DSL script templates to the job-dsl workspace
  become: yes
  template:
    src: "{{ solita_jenkins_jobs_dir }}/{{ item }}"
    dest: "{{ solita_jenkins_job_dsl_workspace }}/{{ item | regex_replace('\\.j2$', '') }}"
    owner: jenkins
    group: jenkins
  with_items:
    - "{{ templates }}"
  register: copy_templates

- name: Remove old Job DSL scripts
  become: yes
  file:
    path: "{{ solita_jenkins_job_dsl_workspace }}/{{ item }}"
    state: absent
    owner: jenkins
    group: jenkins
  with_items: "{{ old_scripts | difference(scripts) | difference(templates | map('regex_replace', '\\.j2$', '') | list) }}"
  register: remove_old_scripts

- name: Run the Job DSL scripts
  shell: >
    {{ solita_jenkins_cli }} build job-dsl -s -v
  when: ((scripts | length > 0) or (templates | length > 0)) and ((copy_scripts | changed) or (copy_templates | changed) or (remove_old_scripts | changed))
